### ISSUE TITLE
Question Regarding a Common Pattern

### ISSUE THREAD

**Issue by eddiewang** [async-library/react-async#143]
Alot of times, the frontend is simply displaying, or transforming the API data from an async call.

One small annoyance i've noticed with the `<IfFufilled state={...} />` / `<IfPending state={...} />` pattern is that the underlying component will flash, leading to an annoying in between state. This is especially annoying if the component is set to poll every X seconds.

This flash effect occurs since the `data` object on the state is removed when a refetch occurs.

One way to avoid the flash during async rereruns is this:
```ts
 // wallet is the state object returned from useAsync() hook
 const [balance, setBalance] = useState(0)
  useEffect(() => {
    if (wallet.data && !wallet.isLoading) {
        setBalance(balance)
    }
  }, [wallet])
```

However, adding a useEffect and a useState just to essentially replace the old data with new data seems convoluted in a sense. I was wondering if anyone else has a better approach to handling this edge case.

**Comment by ghengeveld** [comment]
I'm pretty sure you wouldn't have this issue when you use your own if/else logic instead of the helper components. Just use `useAsync` directly, and don't use `<IfFulfilled>` and the like.
