### ISSUE TITLE
Legacy browser support: Issue with subclassing "Promise"

### ISSUE THREAD

**Issue by rokoroku** [async-library/react-async#174]
Related to #51.
**`react-async`** is hard to use in legacy ES5 browsers due to the implementation of **`NeverSettle`** class. The problem is **subclassing native `Promise`** is not supported in well-known transpilers, and to achieve this we have to polyfill **`Reflect`** and use custom transpilers.

References:
- babel: https://github.com/babel/babel/issues/1120
- typescript: https://github.com/microsoft/TypeScript/issues/15397
> Built-in classes such as Date, Array, DOM etc cannot be properly subclassed due to limitations in ES5 (for the transform-classes plugin). You can try to use babel-plugin-transform-builtin-extend based on Object.setPrototypeOf and Reflect.construct, but it also has some limitations.
> https://babeljs.io/docs/en/caveats/#classes

Let me show an example:
- source:
https://github.com/async-library/react-async/blob/ac09f5ff06ab679b366b1876a06632915682c630/packages/react-async/src/reducer.js#L3-L22

- transpiled (ES5)
```js
var NeverSettle = (function (_super) {
    __extends(NeverSettle, _super);
    function NeverSettle() {
        var _this = _super.call(this, function () { }, function () { }) || this;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    ^ TypeError: undefined is not a promise

        if (Object.setPrototypeOf) {
            Object.setPrototypeOf(_this, NeverSettle.prototype);
        }
        return _this;
    }
    NeverSettle.prototype.finally = function () {
        return this;
    };
    NeverSettle.prototype.catch = function () {
        return this;
    };
    NeverSettle.prototype.then = function () {
        return this;
    };
    return NeverSettle;
}(Promise));
```
- simple reproducible code about the error: 
```js
Promise.call(this, function () {}, function () {})
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
^ TypeError: undefined is not a promise
    at Promise (<anonymous>)
```

So I wish we can change the `NeverSettle` implementation rather than force us to set it up that complex setup. For example:
```js
class NeverSettle {
  constructor() {
    const promise = new Promise(() => {}, () => {});
    this.then = promise.then.bind(promise);
    this.catch = promise.catch.bind(promise);
    this.finally = promise.finally.bind(promise);
  }
}
```

**Comment by rokoroku** [comment]
My current workaround: Just replace the variable `neverSettle` as below. 
```js
const neverSettle = new Promise(() => {}, () => {});
```

The codebase doesn't use `instanceof` check, so it's okay to use like this way.

**Comment by ghengeveld** [comment]
Created a PR here: https://github.com/async-library/react-async/pull/175
So far only reimplemented `NeverSettle`. Still need to handle `FetchError`, but I want to be able to reproduce this first.

**Comment by rokoroku** [comment]
> I've been trying to reproduce the transpilation failure using the Babel REPL, but haven't succeeded to trigger an error so far. What did you do to get these errors?

I also cannot reproduce the issue on the Babel REPL. Maybe there's a patch after babel/babel#1120 (it's quite old issue 😅) 

But it is possible on the Typescript Playground.

http://www.typescriptlang.org/play/?target=1#code/MYGwhgzhAEByCmA3eAnAyvALpk9rwA9N4A7AExgAUUB7AWwEsI8BvaAKGi+BpIkxQBXYJhooAFAEpobTly4RBAB1Tip0ALwA+GQF8ANNHXa90ufID0AKmhNMYEgCNBIWwHMSYvCUKZoViw55LgYAMyMAeUcAK3gRADpmTGoaUUwATxUI0OlZYMtA2FToMEQwBnBHXFsSaABJAFFoAEYABkNnP2AHaEc8JRoQdNCK3DIg-Ogo2ISklLTM+GzxTAALJkMEZHQsHHh4pVoFlTN83Qnoc-MRkjAQIfU84JQsQRRataYLq-luzGBVo8LlwXpg3h91jBzD8uGtSEDzCDXu9oJ8ofIfucgA



> Still need to handle `FetchError`, but I want to be able to reproduce the transpile error before I continue.

Actually, subclassing "Error" doesn't make any problem in my experience so far. (and maybe that is "runtime error" rather than "transpile error"? 😅 )

But just in case, I leave a reference here: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#ES5_Custom_Error_Object

**Comment by ghengeveld** [comment]
Can you verify that the PR I opened works? CodeSandbox automatically packs a release candidate: https://github.com/async-library/react-async/pull/175#issuecomment-540565974

See https://ci.codesandbox.io/status/async-library/react-async/pr/175/builds/333
For usage instructions.

**Comment by rokoroku** [comment]
@ghengeveld I tested your PR in my codebase and now it works (transpiled without any runtime error) well :)

**Comment by ghengeveld** [comment]
Awesome. I'll ship it early next week, as I'm out for the weekend.
