### ISSUE TITLE
useAsync T cannot be null

### ISSUE THREAD

**Issue by jbojcic1** [async-library/react-async#227]
Currently useAsync is defined as `useAsync<T extends {}>` which means it cannot be null or undefined when using ts strict mode.

Example: https://codesandbox.io/s/react-typescript-9x4j1

This makes it impossible to use promise which returns `SomeData | null`

**Comment by ghengeveld** [comment]
That's not right. @Khartir or @phryneas  could you take a look?

**Comment by ghengeveld** [comment]
This is fixed in [v10.0.0](https://github.com/async-library/react-async/releases/tag/v10.0.0) which was released today.
