### ISSUE TITLE
Type of `useFetch` does not include `reload`

### ISSUE THREAD

**Issue by digitalcora** [async-library/react-async#244]
When I do this:

```js
import { useFetch } from "react-async";
const { data, reload } = useFetch("/path/to/api", {});
```

TypeScript complains:

```
TS2339: Property 'reload' does not exist on type 'BaseAsyncState<{}, FetchRun<{}>>'.
```

But if I `@ts-ignore` that line, the `reload` property exists ([as documented](https://docs.react-async.com/api/state#reload)) and works fine.

### Environment

* TypeScript 3.2.2
* React 16.8.1
* react-async 10.0.0

**Comment by ghengeveld** [comment]
Hey, thanks for reporting! Any chance you could open a PR to fix it?

**Comment by digitalcora** [comment]
Sorry, I'm not really sure how to fix the issue myself... I'm new to TypeScript and there's some complicated stuff going on in the type definitions here 😓 I can see that `reload` is expressed in one of the types, but it's unclear to me how that should be making its way to `useFetch`.

**Comment by phryneas** [comment]
That's very weird, because on my system this works:

```ts
// type T = () => void
type T = AsyncState<{}, FetchRun<{}>>['reload']

// const reload: () => void
const { data, reload } = useFetch("/path/to/api", {});
```

What version of TS are you using? What's in your `tsconfig.json`?

**Comment by digitalcora** [comment]
As mentioned above we're on TypeScript 3.2.2. Here is our `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "ts/ts-build",
    "rootDir": ".",
    "lib": [
      "es2017",
      "dom"
    ],
    "strict": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "include": [
    "ts/**/*",
  ],
  "exclude": [
    "node_modules",
    "vendor/",
    "ts/ts-build/"
  ]
}
```

**Comment by phryneas** [comment]
Sorry, had missed that.

It turns out we are using `Omit`, which has only been introduced as an official type with TS 3.5 *sigh*

So we'll need to add 
```ts 
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>; 
```
 to our type definition to satisfy this.

Could you add that somewhere in your `node_modules/react-async/dist-types/index.d.ts` and validate that it fixes your problem please?

**Comment by digitalcora** [comment]
@phryneas Ah, I hadn't realized we were that far behind! I tried adding that code to the top of the file you mentioned, and it does compile without a `@ts-ignore`, so it seems like that would solve the problem if you'd like to support pre-3.5 TypeScript.

**Comment by ghengeveld** [comment]
Closed this due to inactivity. Still happy to take a PR to fix this.
