### ISSUE TITLE
[Feature] : Add a default value for data

### ISSUE THREAD

**Issue by TomPradat** [async-library/react-async#265]
As `initialValue` only works for server-side rendering, it could be nice to have another prop (ex: `defaultDataValue`) so that we can controll the initial value of `data`.

This would improve developer experience with the lib.

**Comment by ghengeveld** [comment]
What's stopping you from using `initialValue` on the client side?
Alternatively, why not use some plain JavaScript to fall back to a default value?

**Comment by TomPradat** [comment]
When using the initialValue on the client side, the `promiseFn` is never called.

As using plain JS, this is what I'm doing but i though it would be less painful having this shipped in the library :

```javascript
const { data: { todos, userPreferences } } = useAsync({ promiseFn, defaultDataValue: { todos: [], userPreferences: null } });
```
vs

```javascript
const { data } = useAsync({ promiseFn });
```

**Comment by TomPradat** [comment]
I agree this is not a mandatory feature but I though this could improve developer experience.

I'm willing to work on this if you're convinced

**Comment by ghengeveld** [comment]
How about:

```js
const { data } = useAsync({ promiseFn });
const { todos = [], userPreferences = null } = data;
```

To be honest I don't think it's worth adding more API options if it can be avoided with a single line of code on the consumer side.

**Comment by TomPradat** [comment]
Yeap i undestand.

Your code doesn't work though because `const { todos = [], userPreferences = null } = undefined;` throws

**Comment by ghengeveld** [comment]
That's easily fixed:
```js
const { data } = useAsync({ promiseFn });
const { todos = [], userPreferences = null } = data || {};
```

**Comment by SachinSharmaE** [comment]
Though i really like the solution of @ghengeveld  still i kind of agree with OP on this. It would be beneficial to have `defaultValue`
