### ISSUE TITLE
How to prevent a deferFn from being run more than once

### ISSUE THREAD

**Issue by justincy** [async-library/react-async#269]
I'm using a `deferFn` so that I can trigger the async action at a later time imperatively via `run()`. I want to make sure `run()` is only called once, so I first check to make sure it hasn't been called yet by examining `isPending` and `isSettled`:

```js
if (!isPending && !isSettled) run()
```

But that doesn't quite work the way I'd expect because sometimes they're false even after `run()` has already been called. Is that supposed to happen?

I found that checking the value of `counter` works more reliably:

```js
if (counter === 0) run()
```

Is that the correct way to do this?

On a side note, even after being called just once, `counter` ends up with the value of 2. Is that supposed to happen? It seems like a bug to me.

**Comment by Haqverdi** [comment]
> I'm using a `deferFn` so that I can trigger the async action at a later time imperatively via `run()`. I want to make sure `run()` is only called once, so I first check to make sure it hasn't been called yet by examining `isPending` and `isSettled`:
> 
> ```js
> if (!isPending && !isSettled) run()
> ```
> 
> But that doesn't quite work the way I'd expect because sometimes they're false even after `run()` has already been called. Is that supposed to happen?
> 
> I found that checking the value of `counter` works more reliably:
> 
> ```js
> if (counter === 0) run()
> ```
> 
> Is that the correct way to do this?
> 
> On a side note, even after being called just once, `counter` ends up with the value of 2. Is that supposed to happen? It seems like a bug to me.

You can use ref, for check can run defer fn or not
example:
```js
  const canRun = React.useRef(true);

  if (canRun.current) {
    run();

    canRun.current = false;
  }

  React.useEffect(() => () => (canRun.current = true), []);
````

**Comment by ghengeveld** [comment]
Hey, sorry I didn't get to this before. I've been crunching on [a major release for Chromatic](https://blog.hichroma.com/chromatic-2-0-code-review-but-for-ui-ddcebf0272b4).

Regarding the value of `counter`, it doesn't represent the number of times you called `run`, but rather the number of times any promise was run (either automatically or manually). Its main purpose is to act as a cache-bust for multiple promises that are triggered in quick succession, to make sure only the most recent one is actually used (the others are cancelled if possible, but failing that their results are simply ignored).

If your goal is to simply disallow running `deferFn` multiple times, I recommend taking the `useRef` approach described by @Haqverdi.
