### ISSUE TITLE
(Docs) Introduction's link to "Concurrent React" is dead

### ISSUE THREAD

**Issue by dtilchin** [async-library/react-async#291]
**Description**

The link "Concurrent React" (pointing to https://github.com/sw-yx/fresh-concurrent-react/blob/master/Intro.md#introduction-what-is-concurrent-react) gives a 404.

**Expected behavior**

All links in the introduction - and any doc section, but especially this one - successfully take the user to useful information

**Detail**

That repo's (renamed) page states that it's unmaintained, so it's probably not a great source to refer users to anymore.

A bandaid fix would be to change the URL to its location as of Nov 2019 ([move / deprecation commit](https://github.com/sw-yx/concurrent-react-notes/commit/c3f1d5525d9ff3ecf8a8ad7d78d7227c71de1598#diff-8708244d48c94a1bd8c0a6f9d1071627) ), which is:
https://github.com/sw-yx/concurrent-react-notes/blob/master/legacy/Intro.md#introduction-what-is-concurrent-react
However, pointing to [React's page on the subject](https://reactjs.org/docs/concurrent-mode-intro.html) sounds like a better bet, long-term.

Relevant line in react-async docs: https://github.com/async-library/react-async/commit/f7b40368a93c7323204fc45c60e140c33291af5a#diff-0970123c5329762d23736c706f9c6caaR32

_(Side note: Is there a tool that periodically follows links in documentation and notifies, perhaps via a github issue, when one leads to a 404 or top-level redirect? I think about that every time I run into one of these)_

**Comment by ghengeveld** [comment]
Fixed. Thank you 🙌
