### ISSUE TITLE
deferFn and promiseFn different behaviour

### ISSUE THREAD

**Issue by hvolschenk** [async-library/react-async#293]
Hiya,

From reading [the documentation](https://docs.react-async.com/api/options#deferfn):

> deferFn ... Receives the same arguments as `promiseFn`

This leads me to believe that calling these two would result in the same parameters being passed to either `deferFn` or `promiseFn` respectively:

```
const promiseState = useAsync({ promiseFn: aaa, projectId: 1 });
// `aaa` called with { projectId: 1 }
// ...
const deferState = useAsync({ deferFn: aaa, projectId: 1 });
deferState.run();
// `aaa` not called with { projectId: 1 }
```

but the `aaa` function above receives different parameters in either configuration.
I have set up a codesandbox here that reproduces the issue: [https://codesandbox.io/s/relaxed-rain-fjpne](https://codesandbox.io/s/relaxed-rain-fjpne).

**Comment by ghengeveld** [comment]
I think this is a wording issue in the docs. The _arguments_ it speaks of are `props: Object, controller: AbortController` which are the same for `promiseFn` and `deferFn`. However, `deferFn` also receives another argument `args` which is what you invoked `run` with (converted to an array).

Would changing _arguments_ to _parameters_ in the docs avoid the confusion between `args` and _arguments_ for you?

Getting back to your example:

```
const deferState = useAsync({ deferFn: aaa, projectId: 1 });
deferState.run();
```

`aaa` here should get called with `[]` as 1st argument and `{ deferFn: aaa, projectId: 1 }` as the 2nd argument.

**Comment by ghengeveld** [comment]
I've updated the docs to clarify. https://github.com/async-library/react-async/commit/ff605ca673600f4ab689f43b529d4beba0f18362
