### ISSUE TITLE
prevent request from executing with useAsync

### ISSUE THREAD

**Issue by JonasBa** [async-library/react-async#297]
Hey, first of all, many thanks for maintaining and creating the project, it's great to work!

I was wondering if there is a way to use `defer` without using `useFetch` like so.

```jsx
useAsync({
    promiseFn: getAsyncSummary,
    defer: !someParamThatMightNotBeSet
})
```

I've tried doing so by returning false from `watchFn`, but it seems that for the first time, the promise is still executed and I couldn't find a nice workaround except by manually calling run inside a useEffect, but I'm not sure that would be the intended usage?

Happy to contribute to the docs or sorry if I missed something obvious!
Thanks a bunch!

**Comment by ghengeveld** [comment]
`defer` is only supported with `useFetch`, not with `useAsync`. If the condition is available on the first render (and preferably never changes), you can do something like this:

```js
useAsync(someParamThatMightNotBeSet ? { promiseFn: getAsyncSummary } : { deferFn: getAsyncSummary })
```

However this means you should also conditionally invoke `run`. I suspect that's not what you're after, but your use case is unclear to me.

If `someParamThatMightNotBeSet` isn't available on first render, you're stuck with using `watch`, `watchFn` or `useEffect`. Here's what you could do with `watch`:

```js
useAsync({ promiseFn, watch: someParamThatMightNotBeSet })
```

Now this will indeed invoke `getAsyncSummary` immediately on first render, regardless of `someParamThatMightNotBeSet`. But you can handle that gracefully by doing something like this:

```js
function promiseFn(props, controller) {
  if (!props.watch) { // the value of someParamThatMightNotBeSet
    return undefined;
  }
  return getAsyncSummary(props, controller)
}
```

The downside here is that `data` is going to get reset to `undefined` each time `someParamThatMightNotBeSet` becomes falsy. A `watchFn` would provide you the flexibility to avoid that (by returning `true` only if some prop goes from falsy to truthy, but not the other way around).

I hope this helps. If not you should probably explain what it really is you're trying to achieve.

**Comment by JonasBa** [comment]
@ghengeveld thanks so much for this detailed reply, you understood the use-case exactly - invoking run manually is not what I'm looking for. It seems that returning undefined will work for me, but I'll have to disable TS there (I wasn't aware that returning undefined would reset data, thank you!). The expected prop should never be falsy afterwards, so I suspect this will work. I'm actually considering moving to useFetch to support this, as it seems to have the mechanism to support this.
