### ISSUE TITLE
Accessing to life cycle hook

### ISSUE THREAD

**Issue by sam13591980** [async-library/react-async#314]
Hello!
How could I have access to life cycle of react-async?
I tested componentDidMount and componentDidUpdate but none of them triggered by react-async full-filled. Basically I want to update this.state when the react-async fullfilled.
Thanks

**Comment by ghengeveld** [comment]
You can use the [`reducer` option](https://docs.react-async.com/api/options#reducer) to fully control the internal state. There's also the [`dispatcher`](https://docs.react-async.com/api/options#dispatcher) which is similar but at a different point in time (before reaching the reducer).
