### ISSUE TITLE
Surface status code in state

### ISSUE THREAD

**Issue by generalpiston** [async-library/react-async#319]
Status codes are useful for front end state management. For example, an API that return 403 and 401 can be treated differently. Also, sometimes APIs return 202 for async processing.

**Comment by generalpiston** [comment]
Here's an example: https://github.com/generalpiston/react-async/commit/b8e3f57d6664500c63932f72aebbac5f7bb057f0.

**Comment by generalpiston** [comment]
Added PR: https://github.com/async-library/react-async/pull/320

**Comment by rstire364** [comment]
Is there any concern about the implications of this change with non-request async functions?

**Comment by generalpiston** [comment]
@rstire364 great point. I didn't think about it. Would it make sense to make it optional?

**Comment by rstire364** [comment]
This might not be a popular answer but I think it's a user-land issue. I would argue this change borders on a violation of separation of concerns. React Async is concerned with providing an abstraction around async state management. 

To be fair, I've used React Async exclusively with Axios, so status and statusCode are readily available. This further reinforces my thought that this is a request library responsibility and not React Async's.

**Comment by generalpiston** [comment]
To your point @rstire364 . I could have also just made `accept` another value as well.

**Comment by rstire364** [comment]
Certainly a valid

**Comment by generalpiston** [comment]
Let's close this then. Thanks @rstire364
